# Illustrative diffs shown on the /demo case-study page's "Code" tab —
# reconstructed from scratch to demonstrate the shape of a real solution,
# not a copy of any employer's actual source.
class DemoCodeDiffs
  def self.all
    [
      DemoDiffFile.new("app/models/chat_assistant.rb", [
        [ :context, "class ChatAssistant < ApplicationRecord" ],
        [ :context, "  # ..." ],
        [ :add, "" ],
        [ :add, "  # Every model our client code knows how to call at all. Appending is" ],
        [ :add, "  # safe; reordering existing entries is not (this backs a Rails enum)." ],
        [ :add, "  KNOWN_MODELS = {" ],
        [ :add, "    \"gpt-3.5-turbo\" => { supports_temperature: true }," ],
        [ :add, "    \"gpt-4\"         => { supports_temperature: true }," ],
        [ :add, "    \"gpt-4.1\"       => { supports_temperature: true }," ],
        [ :add, "    \"gpt-5\"         => { supports_temperature: false }," ],
        [ :add, "    \"gpt-5-mini\"    => { supports_temperature: false }," ],
        [ :add, "    \"gpt-5.4\"       => { supports_temperature: false, forces_reasoning_none: true }" ],
        [ :add, "  }.freeze" ],
        [ :add, "" ],
        [ :add, "  # The one place this string lives — the enum default and the test" ],
        [ :add, "  # factory both point here, so they can't quietly drift out of sync." ],
        [ :add, "  DEFAULT_AI_MODEL = \"gpt-5.4\"" ],
        [ :add, "" ],
        [ :add, "  enum model: KNOWN_MODELS.keys, _default: DEFAULT_AI_MODEL" ],
        [ :add, "" ],
        [ :add, "  # Known models we don't want users picking from the dropdown anymore." ],
        [ :add, "  RESTRICTED_MODELS = %w[gpt-3.5-turbo gpt-4].freeze" ],
        [ :add, "" ],
        [ :add, "  # What actually shows up in the UI: everything known, minus what's restricted." ],
        [ :add, "  def self.selectable_models" ],
        [ :add, "    KNOWN_MODELS.keys - RESTRICTED_MODELS" ],
        [ :add, "  end" ],
        [ :context, "end" ]
      ]),

      DemoDiffFile.new("app/controllers/chat_assistants_controller.rb", [
        [ :context, "class ChatAssistantsController < ApplicationController" ],
        [ :context, "  # ..." ],
        [ :context, "" ],
        [ :context, "  private" ],
        [ :context, "" ],
        [ :remove, "  def chat_assistant_params" ],
        [ :remove, "    params.require(:chat_assistant).permit(:instructions)" ],
        [ :remove, "  end" ],
        [ :add, "  def chat_assistant_params" ],
        [ :add, "    params.require(:chat_assistant).permit(:instructions, :model)" ],
        [ :add, "  end" ],
        [ :context, "end" ]
      ]),

      DemoDiffFile.new("app/models/prompt_builder.rb", [
        [ :context, "class PromptBuilder" ],
        [ :remove, "  def build_request(assistant, params)" ],
        [ :remove, "    base_request(assistant, params)" ],
        [ :remove, "  end" ],
        [ :add, "  def build_request(assistant, params)" ],
        [ :add, "    request = base_request(assistant, params)" ],
        [ :add, "    config = ChatAssistant::KNOWN_MODELS.fetch(assistant.model)" ],
        [ :add, "" ],
        [ :add, "    request.delete(:temperature) unless config[:supports_temperature]" ],
        [ :add, "    request[:reasoning_effort] = \"none\" if config[:forces_reasoning_none]" ],
        [ :add, "" ],
        [ :add, "    request" ],
        [ :add, "  end" ],
        [ :context, "end" ]
      ]),

      DemoDiffFile.new("app/models/chat_assistant.rb", [
        [ :context, "class ChatAssistant < ApplicationRecord" ],
        [ :context, "  validates :instructions, presence: true, allow_nil: true" ],
        [ :add, "" ],
        [ :add, "  validates :model," ],
        [ :add, "    exclusion: { in: RESTRICTED_MODELS }," ],
        [ :add, "    if: :will_save_change_to_model?" ],
        [ :add, "  # A blocklist, not a whitelist: only stops a save from reverting to one" ],
        [ :add, "  # of the specific models above, on the normal save path (e.g. the form)." ],
        [ :add, "  # It doesn't stop testing a new model by hand — that model still has to" ],
        [ :add, "  # exist in KNOWN_MODELS before this code (or the enum) even sees it as" ],
        [ :add, "  # a legal value at all." ],
        [ :context, "end" ]
      ]),

      DemoDiffFile.new("spec/factories/chat_assistants.rb", [
        [ :context, "FactoryBot.define do" ],
        [ :context, "  factory :chat_assistant do" ],
        [ :context, "    channel" ],
        [ :context, "    instructions { \"Answer questions about our product.\" }" ],
        [ :add, "    model { ChatAssistant::DEFAULT_AI_MODEL }" ],
        [ :context, "  end" ],
        [ :context, "end" ]
      ]),

      DemoDiffFile.new("spec/models/prompt_builder_spec.rb", [
        [ :add, "RSpec.describe PromptBuilder do" ],
        [ :add, "  describe \"#build_request\" do" ],
        [ :add, "    context \"when the model supports temperature\" do" ],
        [ :add, "      let(:assistant) { build(:chat_assistant, model: \"gpt-4.1\") }" ],
        [ :add, "" ],
        [ :add, "      it \"keeps temperature in the request\" do" ],
        [ :add, "        request = described_class.new(assistant).build_request" ],
        [ :add, "" ],
        [ :add, "        expect(request[:temperature]).to eq(0.7)" ],
        [ :add, "      end" ],
        [ :add, "" ],
        [ :add, "      it \"does not force a reasoning_effort\" do" ],
        [ :add, "        request = described_class.new(assistant).build_request" ],
        [ :add, "" ],
        [ :add, "        expect(request).not_to have_key(:reasoning_effort)" ],
        [ :add, "      end" ],
        [ :add, "    end" ],
        [ :add, "" ],
        [ :add, "    context \"when the model does not support temperature\" do" ],
        [ :add, "      let(:assistant) { build(:chat_assistant, model: \"gpt-5-mini\") }" ],
        [ :add, "" ],
        [ :add, "      it \"omits temperature from the request\" do" ],
        [ :add, "        request = described_class.new(assistant).build_request" ],
        [ :add, "" ],
        [ :add, "        expect(request).not_to have_key(:temperature)" ],
        [ :add, "      end" ],
        [ :add, "" ],
        [ :add, "      context \"and the model forces reasoning_effort: none\" do" ],
        [ :add, "        let(:assistant) { build(:chat_assistant, model: \"gpt-5.4\") }" ],
        [ :add, "" ],
        [ :add, "        it \"sets reasoning_effort to none\" do" ],
        [ :add, "          request = described_class.new(assistant).build_request" ],
        [ :add, "" ],
        [ :add, "          expect(request[:reasoning_effort]).to eq(\"none\")" ],
        [ :add, "        end" ],
        [ :add, "      end" ],
        [ :add, "" ],
        [ :add, "      context \"and the model does not force a reasoning_effort\" do" ],
        [ :add, "        it \"leaves reasoning_effort unset\" do" ],
        [ :add, "          request = described_class.new(assistant).build_request" ],
        [ :add, "" ],
        [ :add, "          expect(request).not_to have_key(:reasoning_effort)" ],
        [ :add, "        end" ],
        [ :add, "      end" ],
        [ :add, "    end" ],
        [ :add, "  end" ],
        [ :add, "end" ],
        [ :add, "" ],
        [ :add, "RSpec.describe ChatAssistant do" ],
        [ :add, "  it \"rejects a restricted model when the model actually changes\" do" ],
        [ :add, "    assistant = build(:chat_assistant, model: \"gpt-4\")" ],
        [ :add, "" ],
        [ :add, "    expect(assistant).not_to be_valid" ],
        [ :add, "  end" ],
        [ :add, "" ],
        [ :add, "  it \"excludes restricted models from the selectable list\" do" ],
        [ :add, "    expect(described_class.selectable_models).not_to include(\"gpt-4\")" ],
        [ :add, "  end" ],
        [ :add, "end" ]
      ])
    ].freeze
  end
end
