name: Run db:seed (manual)

on:
  workflow_dispatch:

jobs:
  seed:
    name: Seed production database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -a kevinskilton -C "bin/rails db:seed"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
